version: '3.3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/dossier_storage
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    links:
      - fpm
  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    volumes:
      - ./:/var/www/dossier_storage
    links:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - 33062:3306
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dossier_storage